name: Coverage Reporter
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:    # add this line to enable manual trigger
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
        matrix: 
          PYTHON: ["3.10", "3.11"]
    env:
      OS: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.PYTHON }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check for commits in past 24 hours
        id: check
        run: |
          commit_date=$(git log -1 --since='1 day ago' --format="%cd")
          echo "commit_date=$commit_date" >> $GITHUB_OUTPUT
          if [ -n "$commit_date" ]; then
            echo "Commit is found. Running tests and generating coverage report :)"
          else
            echo "No commits made in the last 24 hours, exiting :("
          fi
      - name: Install Dependencies
        if: steps.check.outputs.commit_date != ''
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-cov nbconvert pyyaml matplotlib
      - name: Run Tests and Generate Coverage Report
        if: steps.check.outputs.commit_date != ''
        run: |
          for nb in $(find ./notebooks -name "*.ipynb"); do jupyter nbconvert --to script $nb; done
          tests_to_run=$(python .github/get_tests.py)
          echo "Tests to run: $tests_to_run"
          pytest --cov=. --cov-report xml:coverage.xml $tests_to_run
      - name: Upload coverage to Codacy
        if: steps.check.outputs.commit_date != ''
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          if [ -f coverage.xml ]; then
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
          fi
