name: CI
on:
  push:
    paths:
      - "test/**"
      - "notebooks/**"
      - "simulation/**"
  pull_request:
    paths:
      - "test/**"
      - "notebooks/**"
      - "simulation/**"
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      OS: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.PYTHON }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install minimal dependencies
        run: |
          python -m pip install -U pip
          pip install pyyaml
      - name: Check for tests
        id: check
        run: |
          tests_to_run=$(python .github/get_tests.py)
          echo "tests_to_run=$tests_to_run" >> $GITHUB_OUTPUT
          if [ -n "$tests_to_run" ]; then
            echo "Tests found. Running tests..."
          else
            echo "No tests found. Exiting."
          fi
      - name: Install other Dependencies
        if: steps.check.outputs.tests_to_run != ''
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run Tests
        if: steps.check.outputs.tests_to_run != ''
        run: |
          pytest ${{ steps.check.outputs.tests_to_run }}
      - name: Check for files to test with orjson
        id: check_orjson
        if: steps.check.outputs.tests_to_run != ''
        run: |
          tests_to_run=$(python .github/get_orjson_tests.py)
          echo "tests_to_run=$tests_to_run" >> $GITHUB_OUTPUT
          if [ -n "$tests_to_run" ]; then
            echo "Tests found. Running tests..."
          else
            echo "No tests found. Exiting."
          fi
      - name: Install orjson and rerun tests
        if: steps.check.outputs.tests_to_run != '' && steps.check_orjson.outputs.tests_to_run != ''
        run: |
          pip install orjson
      - name: Rerun Tests with orjson
        if: steps.check.outputs.tests_to_run != '' && steps.check_orjson.outputs.tests_to_run != ''
        run: |
          pytest ${{ steps.check_orjson.outputs.tests_to_run }}
