name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.11"
    steps:
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.11"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install minimal dependencies
        run: |
          python -m pip install -U pip
          pip install pyyaml nbconvert
      - name: Check for tests
        id: check
        run: |
          tests_to_run=$(python .github/get_tests.py)
          echo "::set-output name=tests_to_run::$tests_to_run"
      - name: Exit incase of no tests
        run: |
          if [ -z "${{ steps.check.outputs.tests_to_run }}" ]; then
            echo "No tests to run, exiting"
            exit 0
          fi
      - name: Install other Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run Tests
        run: |
          pytest --cov=. --cov-report xml:coverage.xml ${{ steps.check.outputs.tests_to_run }}

      - name: Print Debug Information
        run: cat get_tests.log
      - name: Verify Python Files in Notebooks Folder
        run: |
          python -c "import os; print(os.listdir('notebooks'))"
      # - name: Upload coverage to Codacy
      #   env:
      #     CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #   run: |
      #     if [ -f coverage.xml ]; then
      #       bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
      #     fi
