name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.11"
    steps:
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.11"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-cov nbconvert pyyaml
      - name: Run Tests and Generate Coverage Report
        run: |
          tests_to_run=$(python get_tests.py)
          echo "Tests to run: $tests_to_run"
          if [[ -n "$tests_to_run" ]]; then
            pytest --cov=. --cov-report xml:coverage.xml $tests_to_run
          fi
      - name: Print Debug Information
        run: cat get_tests.log
      - name: Cleanup converted notebooks
        run: |
          find ./notebooks/ -name "*.py" -type f -delete
      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          if [ -f coverage.xml ]; then
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
          fi
