name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      OS: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.PYTHON }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install minimal dependencies
        run: |
          python -m pip install -U pip
          pip install pyyaml nbconvert
      - name: Check for tests
        id: check
        run: |
          tests_to_run=$(python .github/get_tests.py)
          echo "tests_to_run=$tests_to_run" >> $GITHUB_OUTPUT
          if [ -n "$tests_to_run" ]; then
            echo "Tests found. Running tests..."
          else
            echo "No tests found. Exiting."
          fi
      - name: Install other Dependencies
        if: steps.check.outputs.tests_to_run != ''
        run: |
          pip install -r requirements.txt
          pip install pytest matplotlib
      - name: Run Tests
        if: steps.check.outputs.tests_to_run != ''
        run: |
          pytest ${{ steps.check.outputs.tests_to_run }}
      - name: Print Debug Information
        if: steps.check.outputs.tests_to_run != ''
        run: cat get_tests.log
      - name: Verify Python Files in Notebooks Folder
        if: steps.check.outputs.tests_to_run != ''
        run: |
          python -c "import os; print(os.listdir('notebooks'))"
