name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.11'
    steps:
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.11'
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install coverage
    - name: Run Tests and Generate Coverage Report
      run: |
        coverage run -m unittest discover
        coverage xml
    - name: Upload coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
    - name: Check if coverage.xml is generated
      run: |
        ls -l
